source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'iOSToolboxExample' do

    pod 'CommonCryptoModule', '1.0.2'
    pod 'lottie-ios', '2.5.2'
    pod 'Alamofire', '4.8.0'

end
